MOUSEKEY_ENABLE = yes
# VIA_ENABLE = yes
EXTRAKEY_ENABLE = yes
# NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
UNICODE_ENABLE = yes
RGBLIGHT_ENABLE = no
COMMAND_ENABLE = no
LTO_ENABLE = yes
BOOTMAGIC_ENABLE = no
# LEADER_ENABLE = yes
TAP_DANCE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes

COMBO_ENABLE = yes